<?php

declare(strict_types=1);

// myTinyTodo Database connection configuration

// Generated by My Tiny Todo v2

/*

  Uncomment the line with MTT_DB_TYPE if you make clean install only.

  Leave it commented (with # at start) if you are upgrading from version before 1.7.

  Select the database type: sqlite or mysql or postgres.

*/

namespace App\Config;

/* ===================================================================================================================== */

define('MTT_DB_TYPE', 'sqlite');

define('MTT_DB_HOST', 'localhost');

define('MTT_DB_NAME', 'mytinytodo');

define('MTT_DB_USER', 'mtt');

define('MTT_DB_PASSWORD', 'mtt');

define('MTT_DB_PREFIX', '');

// set mysqli if needed

define('MTT_DB_DRIVER', '');

define('MTT_SALT', '8aa2e054-91fd-4043-8382-ce5f32e1ffa1');
